---
title: "Predição de Votação de Deputados"
author: "Hugo Gabriel"
date: "11 de dezembro de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = TRUE)

library(caret)
library(tidyverse)
```

```{r}
dados_votos <- read.csv("eleicoes2014.csv", encoding = "latin1")

dados_votos <- dados_votos %>%
  select(-c(nome, sequencial_candidato, numero_cadidato, cargo))
# setor_economico_receita, setor_economico_despesa, 
dados_votos[is.na(dados_votos)] <- 0 # Testar com MEDIANA, MÉDIA, ...
```

```{r}
smp_size <- floor(.7*nrow(dados_votos))
set.seed(123)
train_id <- sample(seq_len(nrow(dados_votos)), size = smp_size)

treino <- dados_votos[train_id,]
teste <- dados_votos[-train_id,]

control <- trainControl(method = "repeatedcv", number = 5, repeats = 10, search = "random")
```

### Modelo de Regressão Ridge

```{r}
lambdaGrid <- expand.grid(lambda = 10^seq(10, -2, length=100))

model.ridge <- train(votos~., 
                     data = treino,
                     method = "ridge",
                     trControl = control,
                     preProcess = c('scale', 'center', 'nzv'),
                     tuneGrid = lambdaGrid,
                     metric = "RMSE")

model.ridge

plot(model.ridge$lambda)

model.ridge <- train(votos~., 
                     data = treino,
                     method = "ridge",
                     trControl = control,
                     preProcess = c('scale', 'center', 'nzv'),
                     metric = "RMSE",
                     tuneLength = 10)


model.ridge

ggplot(varImp(model.ridge))
```

### Modelo de Regressão Lasso

```{r}
model.lasso <- train(votos~., 
                     data = treino,
                     method = "lasso",
                     trControl = control,
                     preProcess = c('scale', 'center', 'nzv'),
                     tuneGrid = lambdaGrid,
                     metric = "RMSE",
                     tuneLength = 10)

model.lasso
```

### Modelo de Regressão KNN

```{r}
model.knn <- train(votos~., 
                     data = treino,
                     method = "knn",
                     trControl = control,
                     preProcess = c('scale', 'center', 'nzv'),
                     tuneGrid = lambdaGrid,
                     metric = "RMSE",
                     tuneLength = 10)

model.knn
```

```{r}
plot(model.knn, xvar="lambda")
plot(model.lasso, xvar="lambda")
plot(model.ridge)
```

## Comparando os modelos gerados

## Quais as variáveis mais importantes?

### Ridge
```{r}
ggplot(varImp(model.ridge))
```

### Lasso
```{r}
ggplot(varImp(model.lasso))
```

## Melhor modelo sem validação cruzada


# Testar outros modelos como SVR, Regression Trees, Florestas Aleatórias
# Building Predictive Models in R Using the caret Package (PDF)
